PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <https://data.vlaanderen.be/ns/besluitvorming#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tl: <http://mu.semte.ch/vocabularies/typed-literals/>

SELECT DISTINCT ?agendapunt ?titel ?agenda ?meeting ?geplandeStart ?beslissing ?verslag WHERE {
  {
    SELECT DISTINCT ?agendapunt ?titel WHERE {
      GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
        ?agendapunt a besluit:Agendapunt .
        OPTIONAL { ?agendapunt dct:title ?titel } .
        FILTER NOT EXISTS { ?agendapunt besluitvorming:geagendeerdStuk ?document }
      }
    }
  }
  ?agenda dct:hasPart ?agendapunt .
  ?agenda besluitvorming:isAgendaVoor ?meeting .
  ?meeting besluit:geplandeStart ?geplandeStart .
  ?behandelingVanAgendapunt besluitvorming:heeftOnderwerp ?agendapunt .
  ?behandelingVanAgendapunt besluitvorming:genereertVerslag ?verslag .
  ?behandelingVanAgendapunt besluitvorming:resultaat ?beslissingsResultaatCode .
  ?beslissingsResultaatCode skos:prefLabel ?beslissing .
} ORDER BY DESC(?geplandeStart) ?meeting ?agenda
