PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tl: <http://mu.semte.ch/vocabularies/typed-literals/>

SELECT DISTINCT ?dossier ?dossierTitel ?enigeProcedurestap ?procedurestapTitle ?source WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
    {
      SELECT DISTINCT ?dossier COUNT(DISTINCT ?procedurestap) as ?aantalProcedurestappen ?dossierTitel WHERE {
        {
          SELECT DISTINCT ?verdachteProcedurestap WHERE {
            {
              SELECT COUNT(DISTINCT ?dossier) as ?aantalDossiers ?verdachteProcedurestap WHERE {
                GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
                  ?dossier dossier:doorloopt ?verdachteProcedurestap .
                }
              } ORDER BY desc(?aantalDossiers)
            }
            FILTER (?aantalDossiers > 1)
          }
        }
        ?dossier dossier:doorloopt ?verdachteProcedurestap .
        ?dossier dossier:doorloopt ?procedurestap .
        OPTIONAL { ?dossier dct:title ?dossierTitel . }
      } ORDER BY DESC(?aantalProcedurestappen)
    }
    FILTER (?aantalProcedurestappen = 1)
    ?dossier dossier:doorloopt ?enigeProcedurestap .
    OPTIONAL { ?enigeProcedurestap dct:title ?procedurestapTitle . }
    ?enigeProcedurestap dct:source ?source .
  }
}
