PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tl: <http://mu.semte.ch/vocabularies/typed-literals/>
PREFIX adms: <http://www.w3.org/ns/adms#>

SELECT DISTINCT ?dossier ?aantalProcedurestappen ?dossierIdentifier ?dossierTitle WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
    {
      SELECT DISTINCT ?dossier COUNT(DISTINCT ?procedurestap) as ?aantalProcedurestappen ?dossierTitle ?dossierIdentifier WHERE {
        {
          SELECT DISTINCT ?verdachteProcedurestap WHERE {
            {
              SELECT COUNT(DISTINCT ?dossier) as ?aantalDossiers ?verdachteProcedurestap WHERE {
                GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
                  ?dossier dossier:doorloopt ?verdachteProcedurestap .
                  ?verdachteProcedurestap dct:created ?created .
                }
              } ORDER BY desc(?aantalDossiers)
            }
            FILTER (?aantalDossiers > 1)
          }
        }
        ?dossier dossier:doorloopt ?verdachteProcedurestap .
        ?dossier dossier:doorloopt ?procedurestap .
        ?procedurestap dct:created ?created .
        OPTIONAL { ?dossier dct:title ?dossierTitle . }
        OPTIONAL { ?dossier adms:identifier ?dossierIdentifier . }
      } ORDER BY DESC(?aantalProcedurestappen)
    }
    FILTER (?aantalProcedurestappen > 1)
  }
}
