PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
PREFIX besluitvorming: <https://data.vlaanderen.be/ns/besluitvorming#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tl: <http://mu.semte.ch/vocabularies/typed-literals/>

SELECT COUNT(DISTINCT ?procedurestap) as ?aantalProcedurestappen ?aantalDossiers WHERE {
  {
    SELECT COUNT(DISTINCT ?dossier) as ?aantalDossiers ?procedurestap WHERE {
      GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
        ?dossier dossier:Dossier.isNeerslagVan ?besluitvormingsaangelegenheid .
        ?besluitvormingsaangelegenheid dossier:doorloopt ?procedurestap .
      }
    } ORDER BY desc(?aantalDossiers)
  }
  FILTER (?aantalDossiers > 1)
} ORDER BY desc(?aantalDossiers)
