PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

SELECT DISTINCT ?type ?label  where {
  ?type a ext:ProcedurestapType;
    skos:prefLabel ?label
}
